import { FunctionTestSkeleton, TestGenDigest } from "../types.js";

function skeletonBlock(sk: FunctionTestSkeleton): string[] {
  const lines: string[] = [];
  const sig = sk.signature;
  const params = sig.params.map((p) => `${p.name}: ${p.type}${p.optional ? "?" : ""}`).join(", ");
  lines.push(`describe('${sk.functionName}', () => {`);
  lines.push(`  // signature: ${sig.async ? "async " : ""}${sig.kind} ${sk.functionName}(${params}): ${sig.returnType}`);
  lines.push(`  ${sk.importStatement}`);
  lines.push("");
  for (const c of sk.cases) {
    lines.push(c.body);
    lines.push("");
  }
  lines.push("});");
  return lines;
}

export function formatText(digest: TestGenDigest): string {
  const { skeletons, stats, framework } = digest;
  const lines: string[] = [];

  lines.push(`// generated by testgen — framework: ${framework}`);
  lines.push(`// ${stats.totalFunctions} function(s), ${stats.totalCases} test case(s)`);
  lines.push("");

  if (framework === "vitest") {
    lines.push("import { describe, it, expect } from 'vitest';");
  } else {
    lines.push("// jest is globally available — no import needed");
  }
  lines.push("");

  for (const sk of skeletons) {
    lines.push(...skeletonBlock(sk));
    lines.push("");
  }

  return lines.join("\n");
}
